using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace RealEstateAgency.Models.Mapping
{
    public class EstateFileMap:EntityTypeConfiguration<EstateFile>
    {
        public EstateFileMap()
        {
            ToTable("EstateFile");
            HasKey(e => e.FileID);
            Property(e => e.FileID).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(e => e.PersonID).HasColumnName("PersonID").IsRequired();
            Property(e => e.AddressStreet).HasColumnName("AddressStreet").HasMaxLength(150).IsRequired();
            Property(e => e.AddressAlley).HasColumnName("AddressAlley").HasMaxLength(150).IsRequired();
            Property(e => e.AddressNumber).HasColumnName("AddressNumber").HasMaxLength(10).IsRequired();
            Property(e => e.Area).HasColumnName("Area").HasPrecision(10,2);
            Property(e => e.CityID).HasColumnName("CityID");
            Property(e => e.CreateByID).HasColumnName("CreateByID").IsRequired();
            Property(e => e.Consultant).HasColumnName("Consultant");
            Property(e => e.CreateDate).HasColumnName("CreateDate").IsRequired();
            Property(e => e.EstateType).HasColumnName("EstateType").HasMaxLength(50);
            Property(e => e.FileCode).HasColumnName("FileCode").HasMaxLength(50).IsRequired();
            Property(e => e.FileDescription).HasColumnName("FileDescription").HasMaxLength(1000);
            Property(e => e.FileType).HasColumnName("FileType").HasMaxLength(20);
            Property(e => e.IsDeleted).HasColumnName("IsDeleted").IsRequired();
            Property(e => e.Latitude).HasColumnName("Latitude");
            Property(e => e.Length).HasColumnName("Length").HasPrecision(6,2);
            Property(e => e.Longtitude).HasColumnName("Longtitude");
            Property(e => e.ProvinceID).HasColumnName("ProvinceID").IsRequired();
            Property(e => e.RoomCount).HasColumnName("RoomCount").HasPrecision(2,0).IsRequired();
            Property(e => e.TotalPrice).HasColumnName("TotalPrice").HasPrecision(18,1).IsRequired();
            Property(e => e.UnitPrice).HasColumnName("UnitPrice").HasPrecision(10,1).IsRequired();
            Property(e => e.UpdateByID).HasColumnName("UpdateByID");
            Property(e => e.UpdateDate).HasColumnName("UpdateDate");
            Property(e => e.Width).HasColumnName("Width").HasPrecision(6,2);
            Property(e => e.ZoneID).HasColumnName("ZoneID");
            Property(e => e.BuildingFacade).HasColumnName("BuildingFacade").HasMaxLength(10);
            Property(e => e.Heating).HasColumnName("Heating").HasMaxLength(50);
            Property(e => e.Cooling).HasColumnName("Cooling").HasMaxLength(50);
            Property(e => e.EstatePhoneNumber).HasColumnName("EstatePhoneNumber").HasMaxLength(100);
            Property(e => e.Status).HasColumnName("Status").HasMaxLength(50);//IsRequired().
            Property(e => e.OwnershipDocumentStatus).HasColumnName("OwnershipDocumentStatus").HasMaxLength(100);
            Property(e => e.BuildingFloorCount).HasColumnName("BuildingFloorCount");
            Property(e => e.FloorNumber).HasColumnName("FloorNumber").HasPrecision(3, 0);
            Property(e => e.BuiltUpArea).HasColumnName("BuiltUpArea").HasPrecision(10, 2);
            Property(e => e.Kitchen).HasColumnName("Kitchen").HasMaxLength(10);
            Property(e => e.RestRoom).HasColumnName("RestRoom").HasMaxLength(20);
            Property(e => e.InformationSource).HasColumnName("InformationSource").HasMaxLength(50);
            Property(e => e.HasStoreRoom).HasColumnName("HasStoreRoom").IsRequired();
            Property(e => e.HasElevator).HasColumnName("HasElevator").IsRequired();
            Property(e => e.HasParking).HasColumnName("HasParking").IsRequired();
            Property(e => e.HasRemoteDoor).HasColumnName("HasRemoteDoor").IsRequired();
            Property(e => e.HasServantRestroom).HasColumnName("HasServantRestroom").IsRequired();
            Property(e => e.HasBasement).HasColumnName("HasBasement").IsRequired();
            Property(e => e.HasBackyard).HasColumnName("HasBackyard").IsRequired();
            Property(e => e.HasYard).HasColumnName("HasYard").IsRequired();
            Property(e => e.HasVideoDoorPhone).HasColumnName("HasVideoDoorPhone").IsRequired();
            Property(e => e.NeedToRebuild).HasColumnName("NeedToRebuild").IsRequired();
            Property(e => e.IntegratedSalon).HasColumnName("IntegratedSalon").IsRequired();
            Property(e => e.SeparateSuite).HasColumnName("SeparateSuite").IsRequired();
            Property(e => e.HasLaundryRoom).HasColumnName("HasLaundryRoom").IsRequired();
            Property(e => e.ResidentOwner).HasColumnName("ResidentOwner").IsRequired();
            Property(e => e.IsRealEstate).HasColumnName("IsRealEstate").IsRequired();
            Property(e => e.HasPool).HasColumnName("HasPool").IsRequired();
            Property(e => e.HasSauna).HasColumnName("HasSauna").IsRequired();
            Property(e => e.HasJacuzzi).HasColumnName("HasJacuzzi").IsRequired();
            Property(e => e.HasRoofGarden).HasColumnName("HasRoofGarden").IsRequired();
            Property(e => e.HasConferenceHall).HasColumnName("HasConferenceHall").IsRequired();
            Property(e => e.HasLobby).HasColumnName("HasLobby").IsRequired();
            Property(e => e.HasGym).HasColumnName("HasGym").IsRequired();
            Property(e => e.HasCinema).HasColumnName("HasCinema").IsRequired();
            Property(e => e.HasBilliard).HasColumnName("HasBilliard").IsRequired();
            Property(e => e.HasSquash).HasColumnName("HasSquash").IsRequired();
            Property(e => e.HasRoofPool).HasColumnName("HasRoofPool").IsRequired();
            Property(e => e.HasFurnishedLobby).HasColumnName("HasFurnishedLobby").IsRequired();
            Property(e => e.HasEntrance).HasColumnName("HasEntrance").IsRequired();
            Property(e => e.HasLobbyMan).HasColumnName("HasLobbyMan").IsRequired();
            Property(e => e.HasMaidRoom).HasColumnName("HasMaidRoom").IsRequired();
            Property(e => e.HasSeparateSitting).HasColumnName("HasSeparateSitting").IsRequired();
            Property(e => e.HasInteriorPool).HasColumnName("HasInteriorPool").IsRequired();
            Property(e => e.HasCookingKitchen).HasColumnName("HasCookingKitchen").IsRequired();
            Property(e => e.HasFurnishKitchen).HasColumnName("HasFurnishKitchen").IsRequired();
            Property(e => e.HasSemiFurnishKitchen).HasColumnName("HasSemiFurnishKitchen").IsRequired();
            Property(e => e.HasGardenPermission).HasColumnName("HasGardenPermission").IsRequired();
            Property(e => e.HasRooflessPool).HasColumnName("HasRooflessPool").IsRequired();
            Property(e => e.HasBuildingLicense).HasColumnName("HasBuildingLicense").IsRequired();
            Property(e => e.HasPlanCommand).HasColumnName("HasPlanCommand").IsRequired();
            Property(e => e.HasWatchman).HasColumnName("HasWatchman").IsRequired();
            Property(e => e.InMall).HasColumnName("InMall").IsRequired();
            Property(e => e.HasPatio).HasColumnName("HasPatio").IsRequired();
            Property(e => e.HasSeparateStaircase).HasColumnName("HasSeparateStaircase").IsRequired();
            Property(e => e.HasBigTerrace).HasColumnName("HasBigTerrace").IsRequired();
            Property(e => e.HasPanoramaView).HasColumnName("HasPanoramaView").IsRequired();
            Property(e => e.HasSouthView).HasColumnName("HasSouthView").IsRequired();
            Property(e => e.HasNorthView).HasColumnName("HasNorthView").IsRequired();
            Property(e => e.HasWoodyView).HasColumnName("HasWoodyView").IsRequired();
            Property(e => e.HasResidentialStatus).HasColumnName("HasResidentialStatus").IsRequired();
            Property(e => e.HasGardenDocument).HasColumnName("HasGardenDocument").IsRequired();
            Property(e => e.BoardMountable).HasColumnName("BoardMountable").IsRequired();
            Property(e => e.HasOfficeDocument).HasColumnName("HasOfficeDocument").IsRequired();
            Property(e => e.HasGoodWill).HasColumnName("HasGoodWill").IsRequired();
            Property(e => e.HasOwnership).HasColumnName("HasOwnership").IsRequired();
            Property(e => e.IsFurnitured).HasColumnName("IsFurnitured").IsRequired();
            Property(e => e.ToOutsider).HasColumnName("ToOutsider").IsRequired(); 
            Property(e => e.ParkingCount).HasColumnName("ParkingCount").HasPrecision(2, 0).IsRequired();
            Property(e => e.BuildingAge).HasColumnName("BuildingAge").HasPrecision(2, 0).IsRequired();
            Property(e => e.MasterRoomCount).HasColumnName("MasterRoomCount").HasPrecision(2, 0).IsRequired();
            Property(e => e.StoreRoomArea).HasColumnName("StoreRoomArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.RestRoomCount).HasColumnName("RestRoomCount").HasPrecision(1, 0).IsRequired();
            Property(e => e.UnitCountInFloor).HasColumnName("UnitCountInFloor").HasPrecision(2, 0).IsRequired();
            Property(e => e.ElevatorCount).HasColumnName("ElevatorCount").HasPrecision(1, 0).IsRequired();
            Property(e => e.TerraceArea).HasColumnName("TerraceArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.LobbyCeilingHeight).HasColumnName("LobbyCeilingHeight").HasPrecision(3, 1).IsRequired();
            Property(e => e.UnitCeilingHeight).HasColumnName("UnitCeilingHeight").HasPrecision(3, 1).IsRequired();
            Property(e => e.PassWidth).HasColumnName("PassWidth").HasPrecision(3, 1).IsRequired();
            Property(e => e.YardAread).HasColumnName("YardAread").HasPrecision(5, 1).IsRequired();
            Property(e => e.BasementArea).HasColumnName("BasementArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.FirstFloorArea).HasColumnName("FirstFloorArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.SecondFloorArea).HasColumnName("SecondFloorArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.ThirdFloorArea).HasColumnName("ThirdFloorArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.GroundFloorArea).HasColumnName("GroundFloorArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.DetailedPlanArea).HasColumnName("DetailedPlanArea").HasPrecision(4, 1).IsRequired();
            Property(e => e.KitchenCount).HasColumnName("KitchenCount").HasPrecision(1, 0).IsRequired();
            Property(e => e.BalconyArea).HasColumnName("BalconyArea").HasPrecision(3, 1).IsRequired();
            Property(e => e.AreaForBoard).HasColumnName("AreaForBoard").HasPrecision(3, 1).IsRequired();
            Property(e => e.AllUnitsCount).HasColumnName("AllUnitsCount").HasPrecision(3, 0).IsRequired();
            Property(e => e.AreaForCommerce).HasColumnName("AreaForCommerce").HasPrecision(3, 0).IsRequired();
            Property(e => e.PhoneLineCount).HasColumnName("PhoneLineCount").HasPrecision(2, 0).IsRequired();
            Property(e => e.Flooring).HasColumnName("Flooring").HasMaxLength(50);
            Property(e => e.FacadeMaterial).HasColumnName("FacadeMaterial").HasMaxLength(80);
            Property(e => e.ElevatorBrand).HasColumnName("ElevatorBrand").HasMaxLength(100);
            Property(e => e.ValvesBrand).HasColumnName("ValvesBrand").HasMaxLength(100);
            Property(e => e.BlockPieceNumber).HasColumnName("BlockPieceNumber").HasMaxLength(50);
            Property(e => e.OneWayTwoWayStreet).HasColumnName("OneWayTwoWayStreet").HasMaxLength(10);
            Property(e => e.FloorsArchitecture).HasColumnName("FloorsArchitecture").HasMaxLength(50);
            Property(e => e.JobTenure).HasColumnName("JobTenure").HasMaxLength(50);
            Property(e => e.Deposit).HasColumnName("Deposit").IsRequired().HasPrecision(10, 0);
            Property(e => e.Rent).HasColumnName("Rent").IsRequired().HasPrecision(10, 0);
            HasOptional(e => e.Zone).WithMany(z => z.EstateFiles).HasForeignKey(e => e.ZoneID);
            HasOptional(e => e.City).WithMany(c => c.EstateFiles).HasForeignKey(e => e.CityID).WillCascadeOnDelete(false);
            HasRequired(e => e.Province).WithMany(p => p.EstateFiles).HasForeignKey(e => e.ProvinceID);
            HasRequired(e => e.CreateBy).WithMany(c => c.CreateFile).HasForeignKey(e => e.CreateByID);
            HasOptional(e => e.ConsultantUser).WithMany(u => u.Files_ConsultantUser).HasForeignKey(e => e.Consultant);
            HasRequired(e => e.UpdateBy).WithMany(u => u.UpdateFile).HasForeignKey(e => e.UpdateByID);
            HasRequired(e => e.Person).WithMany(p => p.EstateFiles).HasForeignKey(e => e.PersonID);

        }
    }
}
